#include "efi.h"
#include "OUTPUT/DISPLAY/display.h"
#include "INPUT/KEYBOARD/INPUT_ESC/esc.h"
#include "UI/DRAW/RECOVERYUI/menu.h"
#include "LOADKERNEL/loadkernel.h"
#include "UI/DRAW/LOGO/logo.h"

EFI_SYSTEM_TABLE *gST = NULL;
EFI_BOOT_SERVICES *gBS = NULL;
EFI_RUNTIME_SERVICES *gRT = NULL;
EFI_HANDLE gImageHandle = NULL;

EFI_STATUS efi_main(EFI_HANDLE ImageHandle, EFI_SYSTEM_TABLE *SystemTable) {
    gST = SystemTable;
    gBS = SystemTable->BootServices;
    gRT = SystemTable->RuntimeServices;
    gImageHandle = ImageHandle;

    // Reset console and set background to black, text to white
    gST->ConOut->Reset(gST->ConOut, false);
    gST->ConOut->SetAttribute(gST->ConOut, EFI_WHITE | EFI_BACKGROUND_BLACK);
    gST->ConOut->ClearScreen(gST->ConOut);

    // Initialize GOP for graphics
    InitDisplay();

    // Draw the boot logo (logo_bmp array is generated by xxd from logo.bmp)
    // Now it draws edge-to-edge!
    DrawBmpCentered((void*)logo_bmp, logo_bmp_len);

    // Prompt for ESC
    if (WaitForEscape()) {
        ShowRecoveryMenu();
    }

    // Clear screen again before loading kernel
    ClearScreen(EFI_BACKGROUND_BLACK);

    // Proceed to load the kernel
    LoadKernel();

    // We shouldn't reach here if the kernel successfully loads and jumps
    Print(u"Halted.\r\n");
    while(1) {
        gBS->Stall(1000000);
    }

    return EFI_SUCCESS;
}
